INSERT INTO "table" VALUES(1,'CN','招商银行','经典白金信用卡','白金',NULL,3600,'常见高端卡，年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(2,'CN','招商银行','Young 卡','普卡',NULL,300,'青年客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(3,'CN','招商银行','全币种国际信用卡','金卡',NULL,300,'适合境外消费',NULL,NULL);
INSERT INTO "table" VALUES(4,'CN','招商银行','自由人生白金信用卡','白金',NULL,800,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(5,'CN','建设银行','龙卡全球支付信用卡','白金',NULL,580,'适合境外消费',NULL,NULL);
INSERT INTO "table" VALUES(6,'CN','建设银行','龙卡汽车卡','金卡',NULL,200,'车主权益卡',NULL,NULL);
INSERT INTO "table" VALUES(7,'CN','建设银行','龙卡家庭挚爱信用卡','白金',NULL,580,'家庭消费场景',NULL,NULL);
INSERT INTO "table" VALUES(8,'CN','建设银行','龙卡JOY信用卡','金卡',NULL,160,'年轻客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(9,'CN','中信银行','I 白金信用卡','白金',NULL,480,'网络申请常见卡',NULL,NULL);
INSERT INTO "table" VALUES(10,'CN','中信银行','颜卡信用卡','金卡',NULL,200,'主题卡',NULL,NULL);
INSERT INTO "table" VALUES(11,'CN','中信银行','Safari 卡','白金',NULL,480,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(12,'CN','中信银行','悦卡信用卡','金卡',NULL,200,'消费返利场景',NULL,NULL);
INSERT INTO "table" VALUES(13,'CN','交通银行','Y-POWER 信用卡','金卡',NULL,200,'青年客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(14,'CN','交通银行','标准白金信用卡','白金',NULL,1000,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(15,'CN','交通银行','沃尔玛信用卡','金卡',NULL,150,'商超场景',NULL,NULL);
INSERT INTO "table" VALUES(16,'CN','交通银行','优逸白金信用卡','白金',NULL,500,'差旅场景',NULL,NULL);
INSERT INTO "table" VALUES(17,'CN','浦发银行','美国运通白金信用卡','白金',NULL,3600,'高端权益卡',NULL,NULL);
INSERT INTO "table" VALUES(18,'CN','浦发银行','梦卡信用卡','金卡',NULL,360,'自定义主题卡',NULL,NULL);
INSERT INTO "table" VALUES(19,'CN','浦发银行','AE 运通超白金信用卡','白金',NULL,10000,'高端权益卡',NULL,NULL);
INSERT INTO "table" VALUES(20,'CN','浦发银行','简约白金信用卡','白金',NULL,360,'日常消费卡',NULL,NULL);
INSERT INTO "table" VALUES(21,'CN','光大银行','阳光信用卡','金卡',NULL,200,'标准信用卡',NULL,NULL);
INSERT INTO "table" VALUES(22,'CN','光大银行','抖音联名信用卡','金卡',NULL,200,'联名场景卡',NULL,NULL);
INSERT INTO "table" VALUES(23,'CN','光大银行','凯撒旅游白金信用卡','白金',NULL,1188,'旅行场景卡',NULL,NULL);
INSERT INTO "table" VALUES(24,'CN','平安银行','车主信用卡','金卡',NULL,200,'车主权益卡',NULL,NULL);
INSERT INTO "table" VALUES(25,'CN','平安银行','由你信用卡','金卡',NULL,300,'年轻客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(26,'CN','平安银行','Safari 白金信用卡','白金',NULL,600,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(27,'CN','工商银行','奋斗信用卡','金卡',NULL,200,'年轻客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(28,'CN','工商银行','环球旅行信用卡','白金',NULL,2000,'境外和旅行场景',NULL,NULL);
INSERT INTO "table" VALUES(29,'CN','工商银行','牡丹交通卡','普卡',NULL,100,'地区规则不同',NULL,NULL);
INSERT INTO "table" VALUES(30,'CN','农业银行','漂亮妈妈信用卡','金卡',NULL,200,'家庭消费场景',NULL,NULL);
INSERT INTO "table" VALUES(31,'CN','农业银行','悠然白金信用卡','白金',NULL,580,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(32,'CN','农业银行','燃梦信用卡','金卡',NULL,200,'年轻客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(33,'CN','广发银行','DIY 信用卡','金卡',NULL,80,'自选权益场景',NULL,NULL);
INSERT INTO "table" VALUES(34,'CN','广发银行','臻享白金信用卡','白金',NULL,800,'年费以银行规则为准',NULL,NULL);
INSERT INTO "table" VALUES(35,'CN','广发银行','车主信用卡','金卡',NULL,80,'车主权益卡',NULL,NULL);
INSERT INTO "table" VALUES(36,'CN','民生银行','车车信用卡','金卡',NULL,300,'车主权益卡',NULL,NULL);
INSERT INTO "table" VALUES(37,'CN','民生银行','女人花信用卡','金卡',NULL,300,'女性客群常见卡',NULL,NULL);
INSERT INTO "table" VALUES(38,'CN','兴业银行','PASS 信用卡','金卡',NULL,200,'标准信用卡',NULL,NULL);
INSERT INTO "table" VALUES(39,'CN','兴业银行','行卡白金信用卡','白金',NULL,900,'旅行场景卡',NULL,NULL);
INSERT INTO "table" VALUES(40,'CN','民生银行','百夫长','白金',NULL,NULL,'无限 PP 卡、高额延误险、1800 积点、赠送副卡 900 点、积分可兑换权益和万豪积分。','运通','权益卡');
INSERT INTO "table" VALUES(41,'CN','工商银行','环球白（上海）','白金',NULL,NULL,'无限机场/高铁自营贵宾厅，按 M 会员等级获得龙腾、快速安检、接送机等权益。','Master Card / 银联','权益卡');
INSERT INTO "table" VALUES(42,'CN','招商银行','经典白金卡','白金',NULL,NULL,'300 酒店、机场贵宾厅、体检、洗牙、高尔夫、积分兑换亚万。','VISA / 银联','权益卡,返利卡');
INSERT INTO "table" VALUES(43,'CN','建设银行','尊享白金（大山白）','白金',NULL,NULL,'贵宾厅、体检、龙腾、酒店、接送机、代驾、延误险等权益。','VISA / 银联','权益卡');
INSERT INTO "table" VALUES(44,'CN','农业银行','东航银联（大白）','白金',NULL,NULL,'东航积分兑换，农行大白贵宾厅/贵宾楼权益。','银联','权益卡,联名卡');
INSERT INTO "table" VALUES(45,'CN','农业银行','东航 VISA（小白）','白金',NULL,NULL,'东航积分兑换，适合境外消费，已绝版。','VISA','联名卡');
INSERT INTO "table" VALUES(46,'CN','农业银行','车尊白','白金',NULL,NULL,'代驾、洗车、道路救援等车主权益。','银联','权益卡,返利卡');
INSERT INTO "table" VALUES(47,'CN','浙商银行','长龙航空联名白金','白金',NULL,NULL,'长龙航空积分兑换、机票折扣、赠送银卡。','银联','联名卡');
INSERT INTO "table" VALUES(48,'CN','民生银行','ANA 民生','联名卡',NULL,NULL,'ANA 积分兑换、优先值机、免税店优惠、IHG 酒店相关权益。','JCB / 银联','联名卡');
INSERT INTO "table" VALUES(49,'CN','建设银行','东航睿我万事达','联名卡',NULL,NULL,'东航积分兑换，境外线下刷卡有效。','Master Card','联名卡');
INSERT INTO "table" VALUES(50,'CN','建设银行','muse','返现卡',NULL,NULL,'境外消费返现，全球支付无货币兑换手续费。','VISA','抽屉卡');
INSERT INTO "table" VALUES(51,'CN','中信银行','运通 Safari','白金',NULL,NULL,'消费达标获得积分，可兑换权益。','运通','权益卡');
INSERT INTO "table" VALUES(52,'CN','中信银行','万事达 i 白金','白金',NULL,NULL,'周/月返利活动，日常消费买菜卡。','Master Card / 银联','返利卡');
INSERT INTO "table" VALUES(53,'CN','浙商银行','红利卡','返利卡',NULL,NULL,'消费达标返利。','银联','返利卡');
INSERT INTO "table" VALUES(54,'CN','广发银行','有鱼卡','返利卡',NULL,NULL,'美团、抖音、得物等消费返利。','银联','返利卡');
INSERT INTO "table" VALUES(55,'CN','广发银行','华为车','返利卡',NULL,NULL,'返利活动，需要在 App 内报名。','银联','返利卡');
INSERT INTO "table" VALUES(56,'CN','广发银行','车主白','白金',NULL,NULL,'加油、抵用券、返利相关车主权益。','银联','返利卡');
INSERT INTO "table" VALUES(57,'CN','广发银行','奕驾白','白金',NULL,NULL,'返利、高铁机场贵宾厅、高铁餐食、龙腾机场贵宾等权益。','银联','返利卡,权益卡');
INSERT INTO "table" VALUES(58,'CN','民生银行','MORE 世界卡','世界卡',NULL,NULL,'消费返现，携程钻石会员等权益。','Master Card','抽屉卡');
INSERT INTO "table" VALUES(59,'CN','浦发银行','东航金','金卡',NULL,NULL,'东航积分累计，已注销/活动申请卡。','银联','联名卡');
INSERT INTO "table" VALUES(60,'CN','工商银行','东航联名金','金卡',NULL,NULL,'东航积分累计，境外有分。','Master Card / 银联','联名卡');
INSERT INTO "table" VALUES(61,'CN','招商银行','young 卡（羊毛卡）','金卡',NULL,NULL,'生日月消费活动，30 岁以下办理。','银联','火种卡');
INSERT INTO "table" VALUES(62,'CN','招商银行','JCB 全币种','全币种',NULL,NULL,'日本 JCB 贵宾厅，东南亚和日本可用。','JCB','火种卡');
INSERT INTO "table" VALUES(63,'CN','中信银行','万豪联名（龙年）','联名卡',NULL,NULL,'万豪房晚、积分累计、酒店消费积分、订房优惠，已绝版。','银联','联名卡,返利卡');
INSERT INTO "table" VALUES(64,'CN','中信银行','东航 VISA 卡','联名卡',NULL,NULL,'东航积分兑换，每月积分上限。','VISA','联名卡');
INSERT INTO "table" VALUES(65,'CN','中信银行','国泰航空','联名卡',NULL,NULL,'国泰里程兑换，月里程上限。','Master Card','联名卡');
INSERT INTO "table" VALUES(66,'CN','中信银行','悦卡（金）','金卡',NULL,NULL,'积分倍率，存款达标可作为主力卡。','银联','抽屉卡');
INSERT INTO "table" VALUES(67,'CN','浙商银行','车主卡','车主卡',NULL,NULL,'洗车、停车优惠等车主权益。','银联','返利卡');
INSERT INTO "table" VALUES(68,'CN','广发银行','Visa 鼎极无限卡 2024 巴黎奥运版','无限卡',NULL,NULL,'VISA 鼎极 infinite 级别。','VISA','抽屉卡');
INSERT INTO "table" VALUES(69,'CN','广发银行','东航 IHG 三方联名卡','联名卡',NULL,NULL,'东航/IHG/广发积分累计，无限次高铁贵宾厅。','银联','联名卡');
INSERT INTO "table" VALUES(70,'CN','上海银行','东航白金','白金',NULL,NULL,'东航积分兑换，月里程上限。','银联','联名卡');
INSERT INTO "table" VALUES('demo-cmb-platinum','open-test-user',1,NULL,'0318',5,23,3,18,3,1777014039);
INSERT INTO "table" VALUES('demo-ccb-global','open-test-user',5,NULL,'9527',12,30,NULL,NULL,5,1777014039);
INSERT INTO "table" VALUES('demo-spdb-amex','open-test-user',17,NULL,'8888',20,8,8,8,7,1777014039);
INSERT INTO "table" VALUES('demo-custom-green','open-test-user',NULL,'测试绿色生活卡','6666',28,15,12,31,3,1777014039);
INSERT INTO "table" VALUES('9c3d74f6-9282-4638-8fdd-2c00204ef6e1','2d777618-06d2-47f2-93a6-a1d573efa0c4',9,'123','4123',12,12,3,1,3,1777029583);
INSERT INTO "table" VALUES('9ed10806-e1cf-448b-a33a-63071615b792','2d777618-06d2-47f2-93a6-a1d573efa0c4',9,'213213','1231',4,5,2,3,3,1777034347);
INSERT INTO "table" VALUES('c65a2f91-814e-44c9-a3ea-fc792d7ace9b','2d777618-06d2-47f2-93a6-a1d573efa0c4',45,'123123','1234',3,3,2,2,7,1777035355);
INSERT INTO "table" VALUES('96fb459a-eeb9-47cc-8023-4f99bf45f63c','2d777618-06d2-47f2-93a6-a1d573efa0c4',13,'123123','1234',4,5,1,2,3,1777035399);
INSERT INTO "table" VALUES('bf6e902f-47be-4ece-aa80-fa0f8afdef12','2d777618-06d2-47f2-93a6-a1d573efa0c4','招商银行','景点白金信用卡','白金',NULL,'pending',1777051429);
INSERT INTO "table" VALUES('012670fc-1f15-46d6-a6fe-63e4222002ca','2d777618-06d2-47f2-93a6-a1d573efa0c4','Codex测试银行','端到端巡检信用卡','测试白金','Codex 自动巡检：请忽略，稍后会清理数据库记录。','pending',1777051902);
INSERT INTO "table" VALUES('18edb233-c803-4e10-adcd-38de8727500d','2d777618-06d2-47f2-93a6-a1d573efa0c4','123','213123123','21312312','213123','pending',1777529171);
