-- Attach local card face images to catalog cards.
UPDATE card_catalog SET image_url = '/images/cards/shbank-ceair-platinum.jpg' WHERE bank_name = '上海银行' AND card_name = '东航白金';
UPDATE card_catalog SET image_url = '/images/cards/citic-i-platinum.jpg' WHERE bank_name = '中信银行' AND card_name = 'I 白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/citic-safari.jpg' WHERE bank_name = '中信银行' AND card_name = 'Safari 卡';
UPDATE card_catalog SET image_url = '/images/cards/citic-mastercard-i-platinum.jpg' WHERE bank_name = '中信银行' AND card_name = '万事达 i 白金';
UPDATE card_catalog SET image_url = '/images/cards/citic-marriott-dragon.jpg' WHERE bank_name = '中信银行' AND card_name = '万豪联名（龙年）';
UPDATE card_catalog SET image_url = '/images/cards/citic-ceair-visa.jpg' WHERE bank_name = '中信银行' AND card_name = '东航 VISA 卡';
UPDATE card_catalog SET image_url = '/images/cards/citic-cathay-pacific.jpg' WHERE bank_name = '中信银行' AND card_name = '国泰航空';
UPDATE card_catalog SET image_url = '/images/cards/citic-yue-card.png' WHERE bank_name = '中信银行' AND card_name = '悦卡信用卡';
UPDATE card_catalog SET image_url = '/images/cards/citic-yue-gold.jpg' WHERE bank_name = '中信银行' AND card_name = '悦卡（金）';
UPDATE card_catalog SET image_url = '/images/cards/citic-amex-safari.png' WHERE bank_name = '中信银行' AND card_name = '运通 Safari';
UPDATE card_catalog SET image_url = '/images/cards/citic-yan-card.png' WHERE bank_name = '中信银行' AND card_name = '颜卡信用卡';
UPDATE card_catalog SET image_url = '/images/cards/bocom-y-power.jpg' WHERE bank_name = '交通银行' AND card_name = 'Y-POWER 信用卡';
UPDATE card_catalog SET image_url = '/images/cards/bocom-youyi-platinum.jpg' WHERE bank_name = '交通银行' AND card_name = '优逸白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/bocom-standard-platinum.jpg' WHERE bank_name = '交通银行' AND card_name = '标准白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/bocom-walmart.jpg' WHERE bank_name = '交通银行' AND card_name = '沃尔玛信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ceb-caissa-platinum.png' WHERE bank_name = '光大银行' AND card_name = '凯撒旅游白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ceb-douyin.jpg' WHERE bank_name = '光大银行' AND card_name = '抖音联名信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ceb-sunshine.jpg' WHERE bank_name = '光大银行' AND card_name = '阳光信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cib-pass.jpg' WHERE bank_name = '兴业银行' AND card_name = 'PASS 信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cib-travel-platinum.jpg' WHERE bank_name = '兴业银行' AND card_name = '行卡白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/abc-ceair-visa-small.jpg' WHERE bank_name = '农业银行' AND card_name = '东航 VISA（小白）';
UPDATE card_catalog SET image_url = '/images/cards/abc-ceair-unionpay-big.jpg' WHERE bank_name = '农业银行' AND card_name = '东航银联（大白）';
UPDATE card_catalog SET image_url = '/images/cards/abc-youran-platinum.jpg' WHERE bank_name = '农业银行' AND card_name = '悠然白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/abc-pretty-mom.jpg' WHERE bank_name = '农业银行' AND card_name = '漂亮妈妈信用卡';
UPDATE card_catalog SET image_url = '/images/cards/abc-dream.jpg' WHERE bank_name = '农业银行' AND card_name = '燃梦信用卡';
UPDATE card_catalog SET image_url = '/images/cards/abc-car-platinum.jpg' WHERE bank_name = '农业银行' AND card_name = '车尊白';
UPDATE card_catalog SET image_url = '/images/cards/icbc-ceair-gold.jpg' WHERE bank_name = '工商银行' AND card_name = '东航联名金';
UPDATE card_catalog SET image_url = '/images/cards/icbc-fendou.jpg' WHERE bank_name = '工商银行' AND card_name = '奋斗信用卡';
UPDATE card_catalog SET image_url = '/images/cards/icbc-peony-traffic.jpg' WHERE bank_name = '工商银行' AND card_name = '牡丹交通卡';
UPDATE card_catalog SET image_url = '/images/cards/icbc-global-travel.jpg' WHERE bank_name = '工商银行' AND card_name = '环球旅行信用卡';
UPDATE card_catalog SET image_url = '/images/cards/icbc-global-platinum-shanghai.jpg' WHERE bank_name = '工商银行' AND card_name = '环球白（上海）';
UPDATE card_catalog SET image_url = '/images/cards/pingan-you.jpg' WHERE bank_name = '平安银行' AND card_name = '由你信用卡';
UPDATE card_catalog SET image_url = '/images/cards/pingan-car-owner.jpg' WHERE bank_name = '平安银行' AND card_name = '车主信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-diy.jpg' WHERE bank_name = '广发银行' AND card_name = 'DIY 信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-visa-infinite-paris-2024.jpg' WHERE bank_name = '广发银行' AND card_name = 'Visa 鼎极无限卡 2024 巴黎奥运版';
UPDATE card_catalog SET image_url = '/images/cards/cgb-ceair-ihg.jpg' WHERE bank_name = '广发银行' AND card_name = '东航 IHG 三方联名卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-huawei-car.jpg' WHERE bank_name = '广发银行' AND card_name = '华为车';
UPDATE card_catalog SET image_url = '/images/cards/cgb-yijia-platinum.jpg' WHERE bank_name = '广发银行' AND card_name = '奕驾白';
UPDATE card_catalog SET image_url = '/images/cards/cgb-youyu.jpg' WHERE bank_name = '广发银行' AND card_name = '有鱼卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-zhenxiang-platinum.jpg' WHERE bank_name = '广发银行' AND card_name = '臻享白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-car-owner.jpg' WHERE bank_name = '广发银行' AND card_name = '车主信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cgb-car-owner-platinum.jpg' WHERE bank_name = '广发银行' AND card_name = '车主白';
UPDATE card_catalog SET image_url = '/images/cards/ccb-muse.jpg' WHERE bank_name = '建设银行' AND card_name = 'muse';
UPDATE card_catalog SET image_url = '/images/cards/ccb-ceair-mastercard.jpg' WHERE bank_name = '建设银行' AND card_name = '东航睿我万事达';
UPDATE card_catalog SET image_url = '/images/cards/ccb-dashan-platinum.jpg' WHERE bank_name = '建设银行' AND card_name = '尊享白金（大山白）';
UPDATE card_catalog SET image_url = '/images/cards/ccb-joy.jpg' WHERE bank_name = '建设银行' AND card_name = '龙卡JOY信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ccb-global-payment.jpg' WHERE bank_name = '建设银行' AND card_name = '龙卡全球支付信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ccb-family-love.jpg' WHERE bank_name = '建设银行' AND card_name = '龙卡家庭挚爱信用卡';
UPDATE card_catalog SET image_url = '/images/cards/ccb-auto.jpg' WHERE bank_name = '建设银行' AND card_name = '龙卡汽车卡';
UPDATE card_catalog SET image_url = '/images/cards/cmb-jcb-all-currency.jpg' WHERE bank_name = '招商银行' AND card_name = 'JCB 全币种';
UPDATE card_catalog SET image_url = '/images/cards/cmb-young.jpg' WHERE bank_name = '招商银行' AND card_name = 'Young 卡';
UPDATE card_catalog SET image_url = '/images/cards/cmb-young-wool.jpg' WHERE bank_name = '招商银行' AND card_name = 'young 卡（羊毛卡）';
UPDATE card_catalog SET image_url = '/images/cards/cmb-all-currency.jpg' WHERE bank_name = '招商银行' AND card_name = '全币种国际信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cmb-classic-platinum-credit.jpg' WHERE bank_name = '招商银行' AND card_name = '经典白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cmb-classic-platinum.jpg' WHERE bank_name = '招商银行' AND card_name = '经典白金卡';
UPDATE card_catalog SET image_url = '/images/cards/cmb-free-life-platinum.jpg' WHERE bank_name = '招商银行' AND card_name = '自由人生白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cmbc-ana.jpg' WHERE bank_name = '民生银行' AND card_name = 'ANA 民生';
UPDATE card_catalog SET image_url = '/images/cards/cmbc-more-world.jpg' WHERE bank_name = '民生银行' AND card_name = 'MORE 世界卡';
UPDATE card_catalog SET image_url = '/images/cards/cmbc-woman-flower.png' WHERE bank_name = '民生银行' AND card_name = '女人花信用卡';
UPDATE card_catalog SET image_url = '/images/cards/cmbc-centurion.jpg' WHERE bank_name = '民生银行' AND card_name = '百夫长';
UPDATE card_catalog SET image_url = '/images/cards/cmbc-car.png' WHERE bank_name = '民生银行' AND card_name = '车车信用卡';
UPDATE card_catalog SET image_url = '/images/cards/czbank-bonus.jpg' WHERE bank_name = '浙商银行' AND card_name = '红利卡';
UPDATE card_catalog SET image_url = '/images/cards/czbank-car-owner.jpg' WHERE bank_name = '浙商银行' AND card_name = '车主卡';
UPDATE card_catalog SET image_url = '/images/cards/czbank-loongair-platinum.jpg' WHERE bank_name = '浙商银行' AND card_name = '长龙航空联名白金';
UPDATE card_catalog SET image_url = '/images/cards/spdb-amex-super-platinum.jpg' WHERE bank_name = '浦发银行' AND card_name = 'AE 运通超白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/spdb-ceair-gold.jpg' WHERE bank_name = '浦发银行' AND card_name = '东航金';
UPDATE card_catalog SET image_url = '/images/cards/spdb-dream.jpg' WHERE bank_name = '浦发银行' AND card_name = '梦卡信用卡';
UPDATE card_catalog SET image_url = '/images/cards/spdb-simple-platinum.jpg' WHERE bank_name = '浦发银行' AND card_name = '简约白金信用卡';
UPDATE card_catalog SET image_url = '/images/cards/spdb-amex-platinum.jpg' WHERE bank_name = '浦发银行' AND card_name = '美国运通白金信用卡';
