CREATE TABLE featured_promotions (
  id TEXT PRIMARY KEY,
  bank TEXT NOT NULL,
  partner TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  alt TEXT NOT NULL,
  href TEXT NOT NULL,
  metric_1_label TEXT NOT NULL,
  metric_1_value TEXT NOT NULL,
  metric_2_label TEXT NOT NULL,
  metric_2_value TEXT NOT NULL,
  metric_3_label TEXT NOT NULL,
  metric_3_value TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 100,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

INSERT INTO featured_promotions (
  id, bank, partner, name, description, image_url, alt, href,
  metric_1_label, metric_1_value, metric_2_label, metric_2_value, metric_3_label, metric_3_value,
  sort_order, enabled, created_at, updated_at
) VALUES
  (
    'citic-marriott',
    '中信银行',
    'Marriott Bonvoy',
    '万豪旅享家精逸白金卡',
    '新户 60 天内计积分消费满 30,000 元，可拿 30,000 点万豪积分；叠加消费积分和渠道福利，首年回血空间高于刚性年费。',
    '/images/cards/citic-marriott-bonvoy.webp',
    '中信银行万豪联名信用卡',
    '/refer/citic-marriott',
    '限时奖励',
    '最高 33,000 点',
    '渠道福利',
    '200 元京东 E 卡',
    '持有权益',
    '房券 / 金卡 / 10 晚',
    10,
    1,
    unixepoch(),
    unixepoch()
  ),
  (
    'citic-safari',
    '中信银行',
    'American Express',
    'Safari 联名信用卡',
    '模拟第二张推荐卡：适合关注旅行、餐饮和日常返利的人群。后续可由后台发布活动，替换成真实申请亮点和权益说明。',
    '/images/cards/citic-safari-card-cropped.webp',
    '中信银行 Safari 信用卡',
    '/refer/citic-safari',
    '推荐场景',
    '旅行 / 餐饮',
    '活动状态',
    '模拟展示',
    '后续接入',
    '后台发布',
    20,
    1,
    unixepoch(),
    unixepoch()
  ),
  (
    'citic-airlines',
    '中信银行',
    '航空里程组合',
    '航司联名信用卡',
    '把东航、厦航、川航、南航、海航和深航几张中信航司联名卡放在一起看，适合想按常飞航线、里程价值和办卡活动来选择的人群。',
    '/images/cards/citic-airlines-combo.webp',
    '中信银行航司联名信用卡组合',
    '/refer/citic-airlines',
    '覆盖航司',
    '东航 / 厦航 / 川航',
    '更多选择',
    '南航 / 海航 / 深航',
    '推荐逻辑',
    '按航线和里程选',
    30,
    1,
    unixepoch(),
    unixepoch()
  );
