ALTER TABLE user_cards ADD COLUMN remind_statement INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_cards ADD COLUMN remind_due INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_cards ADD COLUMN remind_annual_fee INTEGER NOT NULL DEFAULT 1;
