-- Generated by scripts/externalize-db-images.mjs.
-- 把数据库内嵌的 base64 图片改为 static 文件路径。所有 UPDATE 都带 data: 前缀守卫，可安全重复执行。

-- 1) 用户卡面若与卡库主图相同，归零让其回退到卡库图片（需在卡库更新前执行）。
UPDATE user_cards SET selected_image_url = NULL
WHERE selected_image_url LIKE 'data:%'
  AND selected_image_url = (SELECT image_url FROM card_catalog c WHERE c.id = user_cards.catalog_id);

-- 2) 卡库主图 data URI -> 静态文件。
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-71.webp' WHERE id = 71 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-72.webp' WHERE id = 72 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-73.webp' WHERE id = 73 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-74.webp' WHERE id = 74 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-75.webp' WHERE id = 75 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-76.webp' WHERE id = 76 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-77.webp' WHERE id = 77 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-78.webp' WHERE id = 78 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-79.webp' WHERE id = 79 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-80.webp' WHERE id = 80 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-81.webp' WHERE id = 81 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-82.webp' WHERE id = 82 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-83.webp' WHERE id = 83 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-84.webp' WHERE id = 84 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-85.webp' WHERE id = 85 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-86.webp' WHERE id = 86 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-87.webp' WHERE id = 87 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-88.webp' WHERE id = 88 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-89.webp' WHERE id = 89 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-90.webp' WHERE id = 90 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-91.webp' WHERE id = 91 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-92.webp' WHERE id = 92 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-93.webp' WHERE id = 93 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-94.webp' WHERE id = 94 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-96.webp' WHERE id = 96 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-97.webp' WHERE id = 97 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-98.webp' WHERE id = 98 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-99.webp' WHERE id = 99 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-100.webp' WHERE id = 100 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-101.webp' WHERE id = 101 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-102.webp' WHERE id = 102 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-103.webp' WHERE id = 103 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-104.webp' WHERE id = 104 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-105.webp' WHERE id = 105 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-106.webp' WHERE id = 106 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-107.webp' WHERE id = 107 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-108.webp' WHERE id = 108 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-109.webp' WHERE id = 109 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-471.webp' WHERE id = 471 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-472.webp' WHERE id = 472 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-473.webp' WHERE id = 473 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-474.webp' WHERE id = 474 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-475.webp' WHERE id = 475 AND image_url LIKE 'data:%';
UPDATE card_catalog SET image_url = '/images/cards/catalog/catalog-476.webp' WHERE id = 476 AND image_url LIKE 'data:%';

-- 3) 卡库 variants JSON 里的 data URI -> 静态文件。
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/catalog-93-v0.webp'
WHERE selected_image_url LIKE 'data:%'
  AND length(selected_image_url) = 368498
  AND substr(selected_image_url, 1, 300) = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABiUAAAPoCAMAAACGaw2FAAAAOVBMVEVXW2FVWV9TV12XmJuwsLHBwMHT0tLj4uP29vbSbUz8cz+bYlSAg4Z2eH1manBhZWteYmhcYGZZXWMLQ3ZKAAQ3BklEQVR42rSX2W7cMAxFB/AseZAt2f//sTV9wDlKNVub9jq0uFxSlBLQyOnrA1yvl/NUSpnvKPkWEQ9K2YEBYL0D1Beg5tzXK7jdq6cPxY2oPcXSCw/uoWkhCNi4G6lbIFkvmvkJCr';
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/catalog-93-v1.webp'
WHERE selected_image_url LIKE 'data:%'
  AND length(selected_image_url) = 395334
  AND substr(selected_image_url, 1, 300) = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABiUAAAPoCAMAAACGaw2FAAAAOVBMVEUsJB8vJyEzKiRJRUJcWlhubGq1tLXLysre3t7z8/OlpKSVlJSLiYl5d3d/fn6Eg4IfGhYkHhkoIRxdV9ObAASFpklEQVR42rSbWY4lOw5DSa7glfe/2P4J4oBCApWvG62qm+EpbEm2Ndmhf34Bz5ZtSbYsWZZkyS7Itr/yhcStl+NC05Jjx0kfSZIWxAn5UO0YiBMnbqkkUGq3ttuf6eWQENsxpemTNk';
UPDATE card_catalog SET variants = '[{"label":"白金卡","imageUrl":"/images/cards/catalog/catalog-93-v0.webp"},{"label":"黑卡","imageUrl":"/images/cards/catalog/catalog-93-v1.webp"}]' WHERE id = 93 AND variants LIKE '%data:image%';
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/catalog-94-v0.webp'
WHERE selected_image_url LIKE 'data:%'
  AND length(selected_image_url) = 19383
  AND substr(selected_image_url, 1, 300) = 'data:image/webp;base64,UklGRq44AABXRUJQVlA4WAoAAAAQAAAA4wEAMAEAQUxQSBsCAAABkGrb1rIt+8fdnchFuCQG0SqXQeMirFJpRKI3BhH+RnPa//F8Dy77PeFzfc5+7YmICcCI2/HSOmHqY3fIGGIM7t+xGzswwdsm5NVz49n13tR8fQx3TdCro6xfM00fH2qPyfrCEOtN2BcHrSnLNva7Z9J+02eXiftqzzt1GYC9Ju9rwE19vQbe6ssAE/iJCwp7ZQr/FRQWsv+y/7L/spmixLqtXKLEgsRiZ';
UPDATE card_catalog SET variants = '[{"label":"白金版","imageUrl":"/images/cards/catalog/catalog-94-v0.webp"}]' WHERE id = 94 AND variants LIKE '%data:image%';

-- 4) 与卡库无关的孤立用户卡面 data URI -> 静态文件。
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/user-2cba5603-c7b0-4a85-848d-48a7c61298b0.webp' WHERE id = '2cba5603-c7b0-4a85-848d-48a7c61298b0' AND selected_image_url LIKE 'data:%';
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/user-6c45faca-51cd-4fa2-be5a-974efbf23d78.webp' WHERE id = '6c45faca-51cd-4fa2-be5a-974efbf23d78' AND selected_image_url LIKE 'data:%';
UPDATE user_cards SET selected_image_url = '/images/cards/catalog/user-a246ce17-865a-449d-84b4-795fd81dc09f.webp' WHERE id = 'a246ce17-865a-449d-84b4-795fd81dc09f' AND selected_image_url LIKE 'data:%';
